FIND_PATH(LOKI_INCLUDE_DIR LokiExport.h /usr/include/loki /usr/local/include/loki)

FIND_LIBRARY(LOKI_LIBRARY NAMES loki PATH /usr/lib /usr/local/lib) 

IF (LOKI_INCLUDE_DIR AND LOKI_LIBRARY)
   SET(LOKI_FOUND TRUE)
ENDIF (LOKI_INCLUDE_DIR AND LOKI_LIBRARY)


IF (LOKI_FOUND)
   IF (NOT LOKI_FIND_QUIETLY)
      MESSAGE(STATUS "Found LOKI: ${LOKI_LIBRARY}")
   ENDIF (NOT LOKI_FIND_QUIETLY)
ELSE (LOKI_FOUND)
   IF (LOKI_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Loki-lib")
   ENDIF (LOKI_FIND_REQUIRED)
ENDIF (LOKI_FOUND)
